name: aniskip
version: 1.0.1

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.10
  freezed:
  json_serializable:
  lints: ^1.0.0

dependencies: 
  freezed_annotation: ^2.0.3
  http: ^0.13.4
  json_annotation: